defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6275014b-4e0d-44f1-ae29-2dac3d16bc75 # Blog Post
handle: blogs
maxAuthors: 1
name: Blogs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  1bbb044e-bdda-4eb7-aaf6-8d8da6510b58: # craftcms-nuxt
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'blogs/{slug}'
structure:
  maxLevels: null
  uid: 4cedcbe1-bbda-4b25-980e-84bd5a9ea3d9
type: structure
