defaultPlacement: end
enableVersioning: true
entryTypes:
  - f5146744-cbea-45a9-9e9e-d5e28fbc0e2d # pages Default
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  1bbb044e-bdda-4eb7-aaf6-8d8da6510b58: # craftcms-nuxt
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'pages/{slug}'
type: channel
