altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fd2587cb-019a-4de7-abe7-aa23bf6bf730:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 978c2aab-8eeb-458a-aba9-2b1d276a2ef6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50302ce3-abf3-40a4-950a-58040212d04a
        userCondition: null
fs: blogImages
handle: blogImages
name: 'Blog Images'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
